channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=41.0.2
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cuda-version=11.7
  - cudatoolkit=11.7.1
  - cudnn=8.8.0.121
  - ffmpeg=4.3
  - filelock=3.9.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.2.10
  - libcurand=10.3.3.141
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgomp=13.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libstdcxx-ng=13.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.25.2
  - numpy-base=1.25.2
  - openh264=2.1.1
  - openssl=3.1.2
  - pillow=9.4.0
  - pip=23.2.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.9.17
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - typing_extensions=4.7.1
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - accelerate==0.22.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - alabaster==0.7.13
      - alembic==1.12.1
      - ampligraph==2.0.1
      - annotated-types==0.5.0
      - argparse==1.4.0
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.1.0
      - auto-gptq==0.3.0+cu117
      - babel==2.13.1
      - beautifultable==1.1.0
      - blis==0.7.10
      - cachetools==5.3.2
      - catalogue==2.0.9
      - cchardet==2.1.7
      - class-resolver==0.4.2
      - click==8.1.7
      - click-default-group==1.2.4
      - colorlog==6.7.0
      - confection==0.1.1
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - cymem==2.0.7
      - dataclasses-json==0.6.1
      - datasets==2.14.4
      - dill==0.3.7
      - docdata==0.0.3
      - docopt==0.6.2
      - docutils==0.17.1
      - en-core-web-sm==3.6.0
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - flake8==6.1.0
      - flatbuffers==23.5.26
      - fonttools==4.45.0
      - frozenlist==1.4.0
      - fsspec==2023.9.0
      - fst-pso==1.8.1
      - fuzzytm==2.0.5
      - gast==0.5.4
      - gensim==4.3.0
      - google-auth==2.23.4
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - greenlet==3.0.1
      - grpcio==1.59.3
      - h5py==3.10.0
      - huggingface-hub==0.16.4
      - imagesize==1.4.1
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - inflect==7.0.0
      - iniconfig==2.0.0
      - isodate==0.6.1
      - joblib==1.3.2
      - jug==2.3.0
      - keras==2.14.0
      - kiwisolver==1.4.5
      - langcodes==3.3.0
      - latexcodec==2.0.1
      - levenshtein==0.21.1
      - libclang==16.0.6
      - mako==1.2.4
      - markdown==3.5.1
      - markdown-it-py==2.2.0
      - marshmallow==3.20.1
      - matplotlib==3.8.2
      - mccabe==0.7.0
      - mdit-py-plugins==0.3.5
      - mdurl==0.1.2
      - miniful==0.0.6
      - ml-dtypes==0.2.0
      - more-click==0.1.2
      - more-itertools==10.1.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - murmurhash==1.0.9
      - mypy-extensions==1.0.0
      - myst-parser==0.18.0
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvcc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.16.5
      - oauthlib==3.2.2
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - optuna==3.4.0
      - packaging==23.1
      - pandas==2.1.0
      - pathy==0.10.2
      - peft==0.5.0
      - pluggy==1.3.0
      - preshed==3.0.8
      - protobuf==4.25.1
      - psutil==5.9.5
      - pyarrow==13.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybtex==0.24.0
      - pybtex-docutils==1.0.3
      - pycodestyle==2.11.1
      - pydantic==2.3.0
      - pydantic-core==2.6.3
      - pyflakes==3.1.0
      - pyfume==0.2.25
      - pygments==2.17.1
      - pyparsing==3.1.1
      - pystow==0.5.2
      - pytest==7.4.3
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - rapidfuzz==3.2.0
      - rdflib==6.3.1
      - regex==2023.8.8
      - requests-oauthlib==1.3.1
      - rexmex==0.1.3
      - rouge==1.0.1
      - rsa==4.9
      - safetensors==0.3.3
      - schema==0.7.5
      - scikit-learn==1.3.2
      - scipy==1.10.0
      - seaborn==0.13.0
      - sentencepiece==0.1.99
      - simpful==2.11.0
      - six==1.16.0
      - smart-open==6.3.0
      - snowballstemmer==2.2.0
      - spacy==3.6.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - sphinx==5.0.2
      - sphinx-rtd-theme==1.0.0
      - sphinxcontrib-applehelp==1.0.7
      - sphinxcontrib-bibtex==2.4.2
      - sphinxcontrib-devhelp==1.0.5
      - sphinxcontrib-htmlhelp==2.0.4
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.6
      - sphinxcontrib-serializinghtml==1.1.9
      - sqlalchemy==2.0.23
      - srsly==2.4.7
      - tabulate==0.9.0
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.1
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorrt==8.5.3.1
      - termcolor==2.3.0
      - thinc==8.1.12
      - threadpoolctl==3.2.0
      - tokenizers==0.13.3
      - tomli==2.0.1
      - torch-max-mem==0.1.3
      - torch-ppr==0.0.8
      - tqdm==4.66.1
      - transformers==4.33.0
      - typer==0.9.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - wasabi==1.1.2
      - wcwidth==0.2.11
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - xformers==0.0.21
      - xlsxwriter==3.1.9
      - xxhash==3.3.0
      - yarl==1.9.2
      - zipp==3.17.0
